server:
  port: 8083
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 121.4.113.134:9092
          zk-nodes: 121.4.113.134:2181
          autoCreateTopics: true
          requiredAcks: 1
          autoAddPartitions: true
      bindings:
        input:
          destination: stream-demo
        output: #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: stream-demo    #消息发往的目的地
          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
  datasource:
    url: jdbc:mysql://121.4.113.134:3306/shipping_app?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: shiwo2002625
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: carrierservice
  redis:
    host: 8.130.92.141
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1

  rabbitmq:
    host: 121.4.113.134
    port: 5672
    username: admin
    password: shiwo2002625
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        #自动签收auto  手动 manual
        acknowledge-mode: manual

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: status
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - orderservice
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
