server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.4.113.134:3306/shipping_app?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: shiwo2002625
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  redis:
    host: 8.130.92.141
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 268022625@qq.com  #发送邮件的邮箱地址
    password: htayerpbukilcacb  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties:
      mail:
        smtp:
          port: 465 #端口号465或587
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    from: 268022625@qq.com  # 发送邮件的地址，和上面username一致
    #    properties.mail.smtp.starttls.enable: true
    #    properties.mail.smtp.starttls.required: true
    #    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: status
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local
#resilience4j:
#  ratelimiter:
#    instances:
#      getEmailCode:
#        limitForPeriod: 2
#        limitRefreshPeriod: 1s
#        timeoutDuration: 0
